# -*- coding: utf-8 -*-
"""Rock Paper Scissor game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1283mKLKl4iVNXJWM-OjmwXRty60ylNHT
"""

import random

# Print multiline instruction
print('Winning rules of the game ROCK PAPER SCISSORS are:\n'
      + "Rock vs Paper -> Paper wins \n"
      + "Rock vs Scissors -> Rock wins \n"
      + "Paper vs Scissors -> Scissors wins \n")

while True:

    print("Enter your choice \n 1 - Rock \n 2 - Paper \n 3 - Scissors \n")

    # Take the input from user
    choice = int(input("Enter your choice: "))

    # Looping until user enters valid input
    while choice > 3 or choice < 1:
        choice = int(input('Enter a valid choice please : '))

    # Initialize value of choice_name variable corresponding to the choice value
    if choice == 1:
        choice_name = 'Rock'
    elif choice == 2:
        choice_name = 'Paper'
    else:
        choice_name = 'Scissors'

    # Print user choice
    print('User choice is:', choice_name)
    print("Now it's Computer's Turn...")

    # Computer chooses randomly any number among 1, 2, and 3
    comp_choice = random.randint(1, 3)

    # Initialize value of comp_choice_name variable corresponding to the choice value
    if comp_choice == 1:
        comp_choice_name = 'Rock'
    elif comp_choice == 2:
        comp_choice_name = 'Paper'
    else:
        comp_choice_name = 'Scissors'

    print("Computer choice is:", comp_choice_name)
    print(choice_name, 'vs', comp_choice_name)

    # Determine the winner and update counts
    if choice == comp_choice:
        result = "DRAW"
        draws += 1
    elif (choice == 1 and comp_choice == 2) or (comp_choice == 1 and choice == 2):
        result = 'Paper'
        if choice == 2:
            user_wins += 1
        else:
            computer_wins += 1
    elif (choice == 1 and comp_choice == 3) or (comp_choice == 1 and choice == 3):
        result = 'Rock'
        if choice == 1:
            user_wins += 1
        else:
            computer_wins += 1
    elif (choice == 2 and comp_choice == 3) or (comp_choice == 2 and choice == 3):
        result = 'Scissors'
        if choice == 3:
            user_wins += 1
        else:
            computer_wins += 1


    # Print the result
    if result == "DRAW":
        print("<== It's a tie! ==>")
    elif result == choice_name:
        print("<== User wins! ==>")
    else:
        print("<== Computer wins! ==>")

    # Ask if the user wants to play again
    print("Do you want to play again? (Y/N)")
    ans = input().lower()
    if ans == 'n':
        break

# After coming out of the while loop, print thanks for playing
print("Thanks for playing!")

import matplotlib.pyplot as plt

# Initialize these variables within or before the game loop
# and increment them based on the game results.
user_wins = 3
computer_wins = 1
draws = 6

# Plot results using matplotlib
labels = ['User Wins', 'Computer Wins', 'Draws']
counts = [user_wins, computer_wins, draws]
plt.bar(labels, counts, color=['green', 'red', 'gray'])
plt.xlabel("Result")
plt.ylabel("Count")
plt.title("Rock Paper Scissors Results")
plt.show()

